### ISSUE TITLE
难以描绘的问题

### ISSUE THREAD

**Issue by bao3** [lijyigithub/ddnspod#2]
如果使用 python2.7

```
SyntaxError: Non-ASCII character '\xe9' in file ddnspod.py on line 116, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

如果使用 python 3

```
raceback (most recent call last):
  File "ddnspod.py", line 131, in <module>
    print(record)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 90-91: ordinal not in range(128)
```

**Comment by lijyigithub** [comment]
我觉得是保存文件的编码问题，可以搜索关键字：python coding。注意一下保存文件时选择的编码。

如果在windows下使用print，文件编码选择的是utf-8，有时候会有问题。linux下没测试过。

或者可以把中文注释全部删除掉

如果还是有问题，建议用一个功能比较全面的编辑器，例如notepad++, sublime text, atom等，选择显示所有字符，看看是不是混进去了什么奇怪的东西。

**Comment by bao3** [comment]
我是直接在 vim 下（Debian ），wget 原文件后就这样，其中 vim 是支持中文的，所以也不乱，所有中文注释也删除了。就是 print 这里过不了

发自我的 iPhone

**Comment by lijyigithub** [comment]
终端使用的字符编码是什么呢？我看了一下dnspod的文档，明确说明了请求和回应都是utf-8编码的（https://www.dnspod.cn/docs/info.html -> API开发规范 -> 4.关于请求）
文件本身也是utf-8的

如果愿意调试的话可以把print改为写入文件，查看一下真实内容是什么，或者把print去掉好了
